### ISSUE TITLE
HowLongToBeat extension causes issues on game description

### ISSUE THREAD

**Issue by Ven0m0** [HexSupernatural/PlayniteModernUIModded#1]
Heres the issue displayed:
https://imgur.com/a/Tox6E5Z
The HowLongToBeat info is displayed over the delevoper, publisher and release date info.

**Comment by 0-Hex** [comment]
Details panel completely reworked in v3.3.0 to respond to this issue

I'm gonna leave this open for now just encase adjustments are needed, as I don't use these extensions so don't have them fully set up

**Comment by Ven0m0** [comment]
this fixes it the issue completely, thank you
